name: Hugo

on:
  push:

  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "hugo"
  cancel-in-progress: true

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.138.0
    steps:
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '${{ env.HUGO_VERSION }}'
          extended: true
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build with Hugo
        env:
          # For maximum backward compatibility with Hugo modules
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          hugo --minify
      - name: Upload artifact
        if: (github.ref != 'refs/heads/main' && github.event_name == 'workflow_dispatch') || github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: www
          path: public
          retention-days: 1

  deploy-production:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    environment:
      url: "http://2025.eswc-conferences.org/"
      name: "Production"
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: www
          path: public

      - name: Copy site to server
        uses: appleboy/scp-action@master
        with:
          host: 2025.eswc-conferences.org
          username: ${{ secrets.PRODUCTION_SSH_USER }}
          key: ${{ secrets.PRODUCTION_SSH_PRIVATE }}
          proxy_host: ${{ secrets.PROXY_HOST }}
          proxy_username: ${{ secrets.PROXY_USERNAME }}
          proxy_key: ${{ secrets.PROXY_KEY }}
          proxy_port: ${{ secrets.PROXY_PORT }}
          source: "public"
          target: "/home/${{ secrets.PRODUCTION_SSH_USER }}/"

      - name: Move site to www
        uses: appleboy/ssh-action@master
        with:
          host: 2025.eswc-conferences.org
          username: ${{ secrets.PRODUCTION_SSH_USER }}
          key: ${{ secrets.PRODUCTION_SSH_PRIVATE }}
          proxy_host: ${{ secrets.PROXY_HOST }}
          proxy_username: ${{ secrets.PROXY_USERNAME }}
          proxy_key: ${{ secrets.PROXY_KEY }}
          proxy_port: ${{ secrets.PROXY_PORT }}
          script: |
            sudo rm -rf /var/www/2025.eswc-conferences.org/
            sudo mkdir -p /var/www/2025.eswc-conferences.org/
            sudo cp -R public/* /var/www/2025.eswc-conferences.org/
            sudo rm -R public
